name: Build All Platforms
run-name: "Build All Platforms: ${{ github.actor }} 🚀"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Desktop:
    strategy:
        matrix:
          include:
          - os: ubuntu
            make_cmd: brebuild
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install cmake pkg-config libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev liblua5.3-dev  -y
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure CMake
        run: make CMAKE_BUILD_TYPE=Release ${{ matrix.make_cmd}}